package com.sapient.Pojo;

public enum OperationConstant {
	ADD, SUBTRACT, MINUS_N_DAYS, MINUS_N_WEEKS, MINUS_N_MONTHS, DAY_OF_WEEK, WEEK_OF_YEAR, PHRASE_CONVERSION,
	CURRENT_SESSION_HISTORY, PREVIOUS_SESSIONS_HISTORY
}
