pipeline{
	agent{ docker{ image 'maven:3.6.3'} }
	
	stages{
		stage ('Compile Stage') {
			steps {
				git "https://github.com/ishikasaini4/PJP2.0.git"
				sh 'mvn clean compile'
			}
		}
		
		stage ('Testing Stage') {
			steps { 
				sh 'mvn test'
			}
		}
		
		stage ('Deployment Stage') {
			steps {
				sh 'mvn deploy'
			}
		}
	}
}